### ISSUE TITLE
Frontend for sudoku solver

### ISSUE THREAD

**Issue by dhirajberi** [dhirajberi/sudoku-solver#1]
- We have 2D matrix (9x9), you just need to create 9x9 matrix UI :)

**Ex:**
board = [["5","3",".",".","7",".",".",".","."],["6",".",".","1","9","5",".",".","."],[".","9","8",".",".",".",".","6","."],["8",".",".",".","6",".",".",".","3"],["4",".",".","8",".","3",".",".","1"],["7",".",".",".","2",".",".",".","6"],[".","6",".",".",".",".","2","8","."],[".",".",".","4","1","9",".",".","5"],[".",".",".",".","8",".",".","7","9"]]

- Replace "." with empty cell

**Comment by MonarthS** [comment]
do we need to create django server too? or just need to create html designs?

**Comment by dhirajberi** [comment]
You can put your html files in "templates" folder.
