### ISSUE TITLE
need api endpoints.

### ISSUE THREAD

**Issue by MonarthS** [dhirajberi/sudoku-solver#5]
I need api endpoint to integrate with UI.

**Comment by dhirajberi** [comment]
https://sudoku-solver-pro.herokuapp.com/isvalid **[POST]**
**In body (JSON)**
{"board":[["5","3",".",".","7",".",".",".","."],["6",".",".","1","9","5",".",".","."],[".","9","8",".",".",".",".","6","."],["8",".",".",".","6",".",".",".","3"],["4",".",".","8",".","3",".",".","1"],["7",".",".",".","2",".",".",".","6"],[".","6",".",".",".",".","2","8","."],[".",".",".","4","1","9",".",".","5"],[".",".",".",".","8",".",".","7","9"]]}

https://sudoku-solver-pro.herokuapp.com/solve **[POST]**
**In body (JSON)**
{"board":[["5","3",".",".","7",".",".",".","."],["6",".",".","1","9","5",".",".","."],[".","9","8",".",".",".",".","6","."],["8",".",".",".","6",".",".",".","3"],["4",".",".","8",".","3",".",".","1"],["7",".",".",".","2",".",".",".","6"],[".","6",".",".",".",".","2","8","."],[".",".",".","4","1","9",".",".","5"],[".",".",".",".","8",".",".","7","9"]]}
